### ISSUE TITLE
OpenGraph description is not set for blog pages

### ISSUE THREAD

**Issue by IMax153** [HiDeoo/starlight-blog#96] opened 2024-12-04 01:25 UTC
### Describe the bug

I'm not exactly sure if this is a bug since this use of `excerpt` may not be intended. However, I was expecting that the `excerpt` of the blog frontmatter be used for the OpenGraph description if no other description is provided.

Feel free to close this issue if this is intended.

### To Reproduce

1. Navigate to the [demo Starlight Blog](https://starlight-blog-docs.vercel.app/blog/sequantur-quaeritis-tandem) and open a blog page
2. Open the browser dev tools and inspect the HTML head
3. Observe the lack of a description

![CleanShot 2024-12-03 at 20 21 00@2x](https://github.com/user-attachments/assets/9b94d9f9-7ef1-430f-b218-d8879740836c)

### Expected behavior

I would expect that the blog `excerpt` could be used as the `og:description` if a `description` is not provided

### How often does this bug happen?

Every time

**Comment by HiDeoo** [comment] 2024-12-04 08:59
Thanks for the feedback :raised_hands: 

The blog plugin actually does no special handling regarding this tag and just fallback to the default Starlight behavior. If a page specify a description through the [`description` frontmatter field](https://starlight.astro.build/reference/frontmatter/#description), it will be used as the meta `og:description` tag value. Otherwise, the [`description` configuration option](https://starlight.astro.build/reference/configuration/#description) will be used if set.

In the given reproduction, the `description` configuration option was omitted (which is now fixed) and as I did not bother manually adding `description` frontmatter fields to the demo pages, the meta `og:description` tag was empty.

Considering that the spec of `og:description` does not recommend any length, I think most of the time, 160 characters is the maximum recommended length for a description which I think is way less than what people usually use for an excerpt. This is one of the reasons why I would be hesitant to automatically use the excerpt as the `og:description` tag value. I'll keep an eye on feedbacks and see if other people have the same idea, and if that's the case, I'll re-evaluate the current behavior.

**Closed by HiDeoo** 2024-12-04 08:59 UTC
